# Generated by Django 4.1 on 2024-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_links_alter_link_tweet_alter_link_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='links',
            field=models.ManyToManyField(null=True, related_name='tweets', to='tweets.link'),
        ),
    ]
