# Generated by Django 4.1 on 2024-09-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_alter_tweet_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='links',
        ),
    ]
